# Generated by Django 4.2.11 on 2024-05-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocole',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
